Flask/5-globomusic/app/album/forms.py
from flask import current_app
# Extension for implementing WTForms for managing web forms
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms.fields import StringField, SubmitField, TextAreaField, FileField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired, DataRequired, Length
# Extension for implementing translations
from flask_babel import lazy_gettext as _l


# General Album form
class AlbumForm(FlaskForm):
	title			= StringField(_l("Title"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=5, max=80, message="Title must be between 5 and 80 characters long")
								])
	artist			= StringField(_l("Artist"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=2, max=30, message="Artist name must be between 2 and 30 characters long")
								])
	description 	= TextAreaField(_l("Description"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=10, max=200, message="Description must be between 10 and 200 characters long")
								])
	genre			= StringField(_l("Genre"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=2, max=20, message="Genre must be between 2 and 20 characters long")
								])

# Form for creating albums
class CreateAlbumForm(AlbumForm):
	release_date	= DateField(_l("Release date"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!")
								],
								format="%Y-%m-%d"
								)
	image		= FileField(_l("Album cover"),
								validators=[
									FileAllowed(current_app.config["ALLOWED_IMAGE_EXTENSIONS"], "Images only!"),
									FileRequired()
								])
	submit 		= SubmitField(_l("Upload album"))

# Form for updating albums
class UpdateAlbumForm(AlbumForm):
	submit 		= SubmitField(_l("Update album information"))

Flask/5-globomusic/app/album/views.py
from flask import current_app #proxy of current app
# Imports from Flask
from flask import Blueprint, render_template, send_from_directory, flash, abort, url_for, redirect
# Extension for implementing Flask-Login for authentication
from flask_login import current_user, login_required
# Extension for implementing translations
from flask_babel import _
from flask_babel import lazy_gettext as _l
# Methods for generating tokens
from secrets import token_hex
# Methods from Werkzeug for managing password hashing and sanitizing filenames
from werkzeug.utils import secure_filename
# Other imports
import os
import datetime
from app import db, cache
from app.models import Album
from app.album.forms import CreateAlbumForm, UpdateAlbumForm
from sqlalchemy.orm import joinedload

album=Blueprint("album", __name__, template_folder="templates")

@cache.cached(timeout=60, key_prefix="list_of_albums")
def get_albums():
    # print("Getting albums from the database")
    return Album.query.options(joinedload(Album.user)).all()

# Route for listing albums
@album.route("/")
@login_required
def list():
    albums = get_albums()
    return render_template("list_albums.html", albums=albums)

# Route for creating new albums
@album.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = CreateAlbumForm()

    if form.validate_on_submit():
        title        = form.title.data
        artist       = form.artist.data
        description  = form.description.data
        genre        = form.genre.data
        image        = save_image_upload(form.image)
        release_date = form.release_date.data

        album = Album(title, artist, description, genre, image, release_date, current_user.id)
        db.session.add(album)
        db.session.commit()
        flash(_("The new album has been added."), "success")
        # This route is attached to album blueprint, add album.
        return redirect(url_for("album.show", slug=album.slug))

    return render_template("create_album.html", form=form)

# Route for updating an album
@album.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    form = UpdateAlbumForm()

    album = Album.query.filter_by(slug=slug).first()

    if not album or not current_user.is_album_owner(album):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))

    if form.validate_on_submit():
        title       = form.title.data
        artist      = form.artist.data
        description = form.description.data
        genre       = form.genre.data

        album.title       = title
        album.artist      = artist
        album.description = description
        album.genre       = genre

        db.session.add(album)
        db.session.commit()
        flash(_("The album has been updated."), "success")
        return redirect(url_for("album.show", slug=album.slug))

    form.title.data       = album.title
    form.artist.data      = album.artist
    form.description.data = album.description
    form.genre.data       = album.genre
    return render_template("edit_album.html", album=album, form=form)

# Route for deleting an album
@album.route("/delete/<slug>", methods=["POST"])
@login_required
def delete(slug):
    album = Album.query.filter_by(slug=slug).first()
    if not album or not current_user.is_album_owner(album):
        flash("You are not authorized to do this.", "danger")
        return redirect(url_for("main.home"))
    db.session.delete(album)
    db.session.commit()
    flash(_("The album has been deleted."), "success")
    return redirect(url_for("main.home"))

# Route for showing an album
@album.route("/show/<slug>")
@login_required
def show(slug):
    album = Album.query.filter_by(slug=slug).first()
    if not album:
        abort(404)
    return render_template("show_album.html", album=album)

# Route for showing the uploaded images
@album.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(current_app.config["IMAGE_UPLOADS"], filename)

# Method for saving an uploaded image to the uploads directory
def save_image_upload(image):
    format = "%Y%m%dT%H%M%S"
    now = datetime.datetime.utcnow().strftime(format)
    random_string = token_hex(2)
    filename = random_string + "_" + now + "_" + image.data.filename
    filename = secure_filename(filename)
    image.data.save(os.path.join(current_app.config["IMAGE_UPLOADS"], filename))
    return filename

Flask/5-globomusic/app/album/templates/create_album.html
{% extends 'base.html' %}
{% block headline %}{{ _('Upload new album') }}{% endblock %}
{% from '_error_messages.html' import error_messages %}
{% set active_page = 'new_album' %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <form method="POST" action="{{ url_for('album.create') }}" enctype="multipart/form-data">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.artist.label }}
        {{ form.artist(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
      </div>
      <div class="form-group">
        {{ form.genre.label }}
        {{ form.genre(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.image.label }}<br>
        {{ form.image }}
      </div>
      <div class="form-group">
        {{ form.release_date.label }}<br>
        {{ form.release_date }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/5-globomusic/app/album/templates/edit_album.html
{% extends 'base.html' %}
{% block headline %}{{ _('Update album information') }} - <a href="{{ url_for('show_album', slug=album.slug) }}">{{ album.title }}</a>{% endblock %}
{% from '_error_messages.html' import error_messages %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <form method="POST" action="{{ url_for('album.edit', slug=album.slug) }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.artist.label }}
        {{ form.artist(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
      </div>
      <div class="form-group">
        {{ form.genre.label }}
        {{ form.genre(class="form-control") }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/5-globomusic/app/album/templates/list_albums.html
{% extends 'base.html' %}
{% set active_page = 'albums' %}
{% block headline %}
  {{ _('Check out these albums') }}
{% endblock %}

{% block content %}
{% if albums %}
{% for album in albums %}
<div class="card text-center mt-3 mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="embed-responsive embed-responsive-1by1">
           <img class="embed-responsive-item" style="object-fit: cover" src="{{ url_for('album.uploads', filename=album.image) }}" alt="">
         </div>
      </div>
      <div class="col-md-6">
        <h5 class="card-title"><a href="{{ url_for('album.show', slug=album.slug) }}">{{ album.title }}</a></h5>
        <p class="card-text">{{ album.artist }}</p>
        <p class="card-text">{{ album.description }}</p>
        <p class="card-text">{{ album.genre }}</p>
        <p class="card-text"><b>{{ _('Release on') }}</b> {{ album.release_date | date_format }}</p>
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    {% if current_user.is_album_owner(album) %}
    {{ _('Posted by you') }}
    {% else %}
    {{ _('Posted by ') }}{{ album.user.username }}
    {% endif %}
  </div>
</div>
{% endfor %}
{% else %}
{{ _('There are no albums to show.') }}
{% endif %}
{% endblock %}

Flask/5-globomusic/app/album/templates/show_album.html
{% extends 'base.html' %}
{% block headline %}Album "{{ album.title }}"{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-5">
    <div class="embed-responsive embed-responsive-1by1">
       <img class="embed-responsive-item" style="object-fit: cover" src="{{ url_for('album.uploads', filename=album.image) }}" alt="">
     </div>
  </div>
  <div class="col-md-5">
    <p><b>{{ _('Title') }}: </b>{{ album.title }}</p>
    <p><b>{{ _('Artist') }}: </b>{{ album.artist }}</p>
    <p><b>{{ _('Description') }}: </b>{{ album.description }}</p>
    <p><b>{{ _('Genre') }}: </b>{{ album.genre }}</p>
    <p><b>{{ _('Release date') }}: </b>{{ album.release_date | date_format }}</p>
    {% if current_user.is_album_owner(album) %}
    <a class="btn btn-info" href="{{ url_for('album.edit', slug=album.slug) }}">{{ _('Edit album') }}</a>
    <form action="{{ url_for('album.delete', slug=album.slug) }}" style="display:inline" method="POST">
      <input type="submit" class="btn btn-danger" value="{{ _('Delete album') }}" onclick="return confirm('{{ _('Are you sure that you want to permanently delete this album?') }}')">
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}