Flask/4-globomantics-users-session-authentication/globomantics/app/gig/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, TextAreaField, DecimalField
from wtforms.validators import InputRequired, DataRequired, Length
from wtforms.widgets import Input
from markupsafe import Markup

class PriceInput(Input):
	input_type = "number"

	def __call__(self, field, **kwargs):
		kwargs.setdefault("id", field.id)
		kwargs.setdefault("type", self.input_type)
		kwargs.setdefault("step", "0.01")
		if "value" not in kwargs:
			kwargs["value"] = field._value()
		if "required" not in kwargs and "required" in getattr(field, "flags", []):
			kwargs["required"] = True
		return Markup("""<div class="input-group mb-3">
			<div class="input-group-prepend">
						<span class="input-group-text">$</span>
					</div>
					<input %s>
		</div>""" % self.html_params(name=field.name, **kwargs))

class PriceField(DecimalField):
	widget = PriceInput()

class GigForm(FlaskForm):
	title		= StringField("Title",
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=5, max=80, message="Title must be between 5 and 80 characters long")
								])
	description = TextAreaField("Description",
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=10, max=200, message="Description must be between 10 and 200 characters long")
								])
	payment		= PriceField("Payment")
	location	= StringField("Location",
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=3, max=40, message="Location must be between 3 and 40 characters long")
								])

class CreateGigForm(GigForm):
	submit 		= SubmitField("Create gig")

class UpdateGigForm(GigForm):
	submit 		= SubmitField("Update gig")

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/views.py
from flask import Blueprint, render_template, request, flash, abort, url_for, redirect
from app.auth.views import current_user, activation_required, login_required, role_required
from app import db
from app.models import User, Role, Gig
from werkzeug.utils import escape, unescape
from app.gig.forms import CreateGigForm, UpdateGigForm
from functools import wraps

gig = Blueprint("gig", __name__, template_folder="templates")

def gig_owner_required(f):
	@wraps(f)
	def _gig_owner_required(*args, **kwargs):
		gig = Gig.query.filter_by(slug=request.view_args["slug"]).first()
		if not gig or not current_user.is_gig_owner(gig):
			flash("You are not the owner of that gig.", "danger")
			return redirect(url_for("main.home"))
		return f(*args, **kwargs)
	return _gig_owner_required

@gig.route("/create", methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
def create():
	form = CreateGigForm()

	if form.validate_on_submit():
		title		= escape(form.title.data)
		description = escape(form.description.data)
		payment		= form.payment.data
		location	= escape(form.location.data)

		gig = Gig(title, description, payment, location, current_user.id)
		db.session.add(gig)
		db.session.commit()
		flash("The new gig has been added. \""+ gig.title +"\"", "success")
		return redirect(url_for("gig.show", slug=gig.slug))

	return render_template("create_gig.html", form=form)

@gig.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def edit(slug):
	form = UpdateGigForm()

	gig = Gig.query.filter_by(slug=slug).first()

	if form.validate_on_submit():
		gig.title		= escape(form.title.data)
		gig.description = escape(form.description.data)
		gig.payment		= form.payment.data
		gig.location	= escape(form.location.data)

		db.session.add(gig)
		db.session.commit()
		flash("The gig is updated.", "success")
		return redirect(url_for("gig.show", slug=gig.slug))

	form.title.data			= unescape(gig.title)
	form.description.data 	= unescape(gig.description)
	form.payment.data		= gig.payment
	form.location.data		= unescape(gig.location)
	return render_template("edit_gig.html", gig=gig, form=form)

@gig.route("/delete/<slug>", methods=["POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def delete(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    db.session.delete(gig)
    db.session.commit()
    flash("The gig is deleted.", "success")
    return redirect(url_for("main.home"))

@gig.route("/info/<slug>")
@login_required
@activation_required
def show(slug):
	gig = Gig.query.filter_by(slug=slug).first()
	if not gig:
		abort(404)
	musicians = gig.musicians.all()
	return render_template("show_gig.html", gig=gig, musicians=musicians)

@gig.route("/my_gigs")
@login_required
@activation_required
def my_gigs():
	gigs = None
	if current_user.is_role(Role.MUSICIAN):
		gigs = current_user.applied_gigs.all()
	if current_user.is_role(Role.EMPLOYER):
		gigs = current_user.gigs.all()

	return render_template("my_gigs.html", gigs=gigs)

@gig.route("/apply/<slug>", methods=["POST"])
@login_required
@activation_required
@role_required(Role.MUSICIAN)
def apply_to_gig(slug):
	gig = Gig.query.filter_by(slug=slug).first()
	if not gig:
		abort(404)

	current_user.apply(gig)
	db.session.commit()

	flash("You just applied to the gig: \"" + gig.title + "\".", "success")
	return redirect(request.referrer)

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/templates/_gig.html
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <div class="card-body">
      <div class="embed-responsive embed-responsive-16by9" style="margin-bottom:10px">
        <a href="">
          <img class="card-img-top embed-responsive-item" src="{{ url_for('static', filename='images/gig.png') }}" alt="">
        </a>
      </div>
      <h4 class="card-title">
        <a href="{{ url_for('gig.show', slug=gig.slug) }}">{{ gig.title }}</a>
      </h4>
      <h5>{{ "$%.2f" | format(gig.payment) }}</h5>
      <p>{{ gig.location }}</p>
      <p class="card-text">{{ gig.description }}</p>
    </div>
    <div class="card-footer">
      <small>Posted by: <a href="{{ url_for('account.show', username=gig.employer.username) }}">{{ gig.employer.username }}</a></small>
      {% if active_page == 'home' %}
        {% if current_user.is_role(Role.MUSICIAN) %}
          <br>
          {% if current_user.is_applied_to(gig) %}
           <button class="btn btn-warning" style="color:white;margin-top:10px" disabled>Applied...</button>
          {% else %}
          <form method="POST" action="{{ url_for('gig.apply_to_gig', slug=gig.slug) }}">
            <input type="submit" class="btn btn-warning" style="color:white;margin-top:10px" value="Apply">
          </form>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/templates/create_gig.html
{% extends 'base.html' %}
{% block title %}Create new gig - {% endblock %}
{% from '_error_messages.html' import field_error_messages, error_messages %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Create new gig</h1><hr>
    <form method="POST" action="{{ url_for('gig.create') }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
        {{ field_error_messages(form.title) }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
        {{ field_error_messages(form.description) }}
      </div>
      <div class="form-group">
        {{ form.payment.label }}
        {{ form.payment(class="form-control") }}
        {{ field_error_messages(form.payment) }}
      </div>
      <div class="form-group">
        {{ form.location.label }}
        {{ form.location(class="form-control") }}
        {{ field_error_messages(form.location) }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/templates/edit_gig.html
{% extends 'base.html' %}
{% block title %}Edit gig {{ gig.title }} - {% endblock %}
{% from '_error_messages.html' import field_error_messages, error_messages %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Edit gig - <a href="{{ url_for('gig.show', slug=gig.slug) }}">{{ gig.title }}</a></h1><hr>
    <form method="POST" action="{{ url_for('gig.edit', slug=gig.slug) }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
        {{ field_error_messages(form.title) }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
        {{ field_error_messages(form.description) }}
      </div>
      <div class="form-group">
        {{ form.payment.label }}
        {{ form.payment(class="form-control") }}
        {{ field_error_messages(form.payment) }}
      </div>
      <div class="form-group">
        {{ form.location.label }}
        {{ form.location(class="form-control") }}
        {{ field_error_messages(form.location) }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/templates/my_gigs.html
{% extends 'base.html' %}
{% set active_page = 'my_gigs'  %}
{% block title %}My gigs - {% endblock %}

{% block content %}
{% if gigs %}
<h1 class="my-4">
	{% if current_user.is_role(Role.MUSICIAN) %}
	Gigs that you applied to
	{% endif %}
	{% if current_user.is_role(Role.EMPLOYER) %}
	Gigs that you have posted
	{% endif %}
</h1>
<div class="row">
	<div class="col-lg-10">
		<div class="row my-4 card-wrapper">
{% for gig in gigs %}
	{% include '_gig.html' %}
{% endfor %}
		</div>
	</div>
</div>
{% else %}
<div class="alert alert-danger alert-dismissible my-4" role="alert">
  There are no gigs to show.
</div>
{% endif %}
{% endblock %}

Flask/4-globomantics-users-session-authentication/globomantics/app/gig/templates/show_gig.html
{% extends 'base.html' %}
{% block title %}{{ gig.title }} - {% endblock %}

{% block content %}
<div class="row">

  <div class="col-lg-10">
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">
          <img class="gig-image" src="{{ url_for('static', filename='images/gig.png') }}" alt="">
          {{ gig.title }}
        {% if gig.employer == current_user %}
        <div class="button-actions">
          <a href="{{ url_for('gig.edit', slug=gig.slug) }}" class="btn btn-primary">Update gig</a>
          <form class="delete-form" method="POST" action="{{ url_for('gig.delete', slug=gig.slug) }}">
            <input class="btn btn-danger" type="submit" name="deleteGig"
              value="Delete gig"
              onclick="return confirm('Are you sure that you want to permanently delete this gig?')">
          </form>
        </div>
	      {% endif %}
        {% if current_user.is_role(Role.MUSICIAN) %}
          <div class="button-actions">
          {% if current_user.is_applied_to(gig) %}
            <button class="btn btn-warning" style="color:white" disabled>Applied...</button>
          {% else %}
            <form method="POST" action="{{ url_for('gig.apply_to_gig', slug=gig.slug) }}">
              <input type="submit" class="btn btn-warning" style="color:white" value="Apply">
            </form>
          {% endif %}
          </div>
        {% endif %}
	      </h3>
        <h4>{{ "$%.2f" | format(gig.payment) }}</h4>
        <p><b>Location:</b> {{ gig.location }}</p>
        <p class="card-text">{{ gig.description }}</p>
        <small>Posted by: <a href="{{ url_for('account.show', username=gig.employer.username) }}">{{ gig.employer.username }}</a></small>
      </div>
    </div>


    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Musicians applied to this gig
      </div>
      <div class="card-body">
        {% if musicians %}
        {% for musician in musicians %}
        <h4><a href="{{ url_for('account.show', username=musician.username) }}">{{ musician.username }}</a><h4>
        <hr class="form-border">
        {% endfor %}
        {% else %}
        Nothing to show
        {% endif %}
      </div>
    </div>
  </div>

</div>
{% endblock %}