Flask/5-globomusic/app/album/views.py
from flask import current_app #proxy of current app
# Imports from Flask
from flask import Blueprint, render_template, send_from_directory, flash, abort, url_for, redirect
# Extension for implementing Flask-Login for authentication
from flask_login import current_user, login_required
# Extension for implementing translations
from flask_babel import _
from flask_babel import lazy_gettext as _l
# Methods for generating tokens
from secrets import token_hex
# Methods from Werkzeug for managing password hashing and sanitizing filenames
from werkzeug.utils import secure_filename
# Other imports
import os
import datetime
from app import db, cache
from app.models import Album
from app.album.forms import CreateAlbumForm, UpdateAlbumForm
from sqlalchemy.orm import joinedload

album=Blueprint("album", __name__, template_folder="templates")

@cache.cached(timeout=60, key_prefix="list_of_albums")
def get_albums():
    # print("Getting albums from the database")
    return Album.query.options(joinedload(Album.user)).all()

# Route for listing albums
@album.route("/")
@login_required
def list():
    albums = get_albums()
    return render_template("list_albums.html", albums=albums)

# Route for creating new albums
@album.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = CreateAlbumForm()

    if form.validate_on_submit():
        title        = form.title.data
        artist       = form.artist.data
        description  = form.description.data
        genre        = form.genre.data
        image        = save_image_upload(form.image)
        release_date = form.release_date.data

        album = Album(title, artist, description, genre, image, release_date, current_user.id)
        db.session.add(album)
        db.session.commit()
        flash(_("The new album has been added."), "success")
        # This route is attached to album blueprint, add album.
        return redirect(url_for("album.show", slug=album.slug))

    return render_template("create_album.html", form=form)

# Route for updating an album
@album.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    form = UpdateAlbumForm()

    album = Album.query.filter_by(slug=slug).first()

    if not album or not current_user.is_album_owner(album):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))

    if form.validate_on_submit():
        title       = form.title.data
        artist      = form.artist.data
        description = form.description.data
        genre       = form.genre.data

        album.title       = title
        album.artist      = artist
        album.description = description
        album.genre       = genre

        db.session.add(album)
        db.session.commit()
        flash(_("The album has been updated."), "success")
        return redirect(url_for("album.show", slug=album.slug))

    form.title.data       = album.title
    form.artist.data      = album.artist
    form.description.data = album.description
    form.genre.data       = album.genre
    return render_template("edit_album.html", album=album, form=form)

# Route for deleting an album
@album.route("/delete/<slug>", methods=["POST"])
@login_required
def delete(slug):
    album = Album.query.filter_by(slug=slug).first()
    if not album or not current_user.is_album_owner(album):
        flash("You are not authorized to do this.", "danger")
        return redirect(url_for("main.home"))
    db.session.delete(album)
    db.session.commit()
    flash(_("The album has been deleted."), "success")
    return redirect(url_for("main.home"))

# Route for showing an album
@album.route("/show/<slug>")
@login_required
def show(slug):
    album = Album.query.filter_by(slug=slug).first()
    if not album:
        abort(404)
    return render_template("show_album.html", album=album)

# Route for showing the uploaded images
@album.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(current_app.config["IMAGE_UPLOADS"], filename)

# Method for saving an uploaded image to the uploads directory
def save_image_upload(image):
    format = "%Y%m%dT%H%M%S"
    now = datetime.datetime.utcnow().strftime(format)
    random_string = token_hex(2)
    filename = random_string + "_" + now + "_" + image.data.filename
    filename = secure_filename(filename)
    image.data.save(os.path.join(current_app.config["IMAGE_UPLOADS"], filename))
    return filename

Flask/5-globomusic/app/tour/views.py
# Imports from Flask
from flask import Blueprint, render_template, flash, abort, url_for, redirect
# Extension for implementing Flask-Login for authentication
from flask_login import current_user, login_required
# Extension for implementing translations
from flask_babel import _
from flask_babel import lazy_gettext as _l
from app import db
from app.models import Tour
from app.tour.forms import CreateTourForm, UpdateTourForm

tour=Blueprint("tour", __name__, template_folder="templates")


# Route for listing tours
@tour.route("/")
@login_required
def list():
    tours = Tour.query.all()
    return render_template("list_tours.html", tours=tours)

# Route for creating new tours
@tour.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = CreateTourForm()

    if form.validate_on_submit():
        title        = form.title.data
        artist       = form.artist.data
        description  = form.description.data
        genre        = form.genre.data
        start_date   = form.start_date.data
        end_date     = form.end_date.data

        tour = Tour(title, artist, description, genre, start_date, end_date, current_user.id)
        db.session.add(tour)
        db.session.commit()
        flash(_("The new tour has been added."), "success")
        return redirect(url_for("tour.show", slug=tour.slug))

    return render_template("create_tour.html", form=form)

# Route for updating a tour
@tour.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    form = UpdateTourForm()

    tour = Tour.query.filter_by(slug=slug).first()

    if not tour or not current_user.is_tour_owner(tour):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))

    if form.validate_on_submit():
        title       = form.title.data
        artist      = form.artist.data
        description = form.description.data
        genre       = form.genre.data
        start_date  = form.start_date.data
        end_date    = form.end_date.data

        tour.title       = title
        tour.artist      = artist
        tour.description = description
        tour.genre       = genre
        tour.start_date  = start_date
        tour.end_date    = end_date

        db.session.add(tour)
        db.session.commit()
        flash(_("The tour has been updated."), "success")
        return redirect(url_for("tour.show", slug=tour.slug))

    form.title.data       = tour.title
    form.artist.data      = tour.artist
    form.description.data = tour.description
    form.genre.data       = tour.genre
    form.start_date.data  = tour.start_date
    form.end_date.data    = tour.end_date
    return render_template("edit_tour.html", tour=tour, form=form)

# Route for deleting a tour
@tour.route("/delete/<slug>", methods=["POST"])
@login_required
def delete(slug):
    tour = Tour.query.filter_by(slug=slug).first()
    if not tour or not current_user.is_tour_owner(tour):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))
    db.session.delete(tour)
    db.session.commit()
    flash(_("The tour has been deleted."), "success")
    return redirect(url_for("main.home"))

# Route for showing a tour
@tour.route("/show/<slug>")
@login_required
def show(slug):
    tour = Tour.query.filter_by(slug=slug).first()
    if not tour:
        abort(404)
    return render_template("show_tour.html", tour=tour)

Flask/5-globomusic/app/templates/_error_messages.html
{% macro error_messages(errors) %}
{% if errors %}
<div class="alert alert-danger">
  {% for field in errors %}
    <b>{{ field | capitalize }} field has following errors:</b><br>
    {% for error in errors[field] %}
    {{ error }}<br>
    {% endfor %}
  {% endfor %}
</div>
{% endif %}
{% endmacro %}

Flask/5-globomusic/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GloboMusic</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-info flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ url_for('main.home') }}">GloboMusic</a>
      {% if current_user.is_authenticated %}
      <span class="navbar-brand col-sm-3 col-md-3 mr-0">{{ _('You are logged in as') }} {{ current_user.username }}!</span>
      {% endif %}
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              {% if current_user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link {{ 'active' if active_page == 'home' }}" href="{{ url_for('main.home') }}">
                  {{ _('Home') }}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'active' if active_page == 'login' }}" href="{{ url_for('auth.login') }}">
                  {{ _('Login') }}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'active' if active_page == 'register' }}" href="{{ url_for('auth.register') }}">
                  {{ _('Register') }}
                </a>
              </li>
              {% else %}
              {% if current_user.is_admin %}
              {% for view_name in config["ADMIN_VIEWS"] %}
              <li class="nav-item {% if loop.last %}mb-3{% endif %}">
                <a class="nav-link {{ 'active' if active_page == 'admin_'+view_name }}" href="{{ url_for('admin.{}_table'.format(view_name)) }}">
                  Manage {{ view_name }} model
                </a>
              </li>
              {% endfor %}
              {% endif %}
              <li class="nav-item">
                <a class="nav-link {{ 'active' if active_page == 'albums' }}" href="{{ url_for('album.list') }}">
                  {{ _('See albums') }}
                </a>
              </li>
              <li class="nav-item mb-2">
                <a class="nav-link {{ 'active' if active_page == 'tours' }}" href="{{ url_for('tour.list') }}">
                  {{ _('See tours') }}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'active' if active_page == 'new_album' }}" href="{{ url_for('album.create') }}">
                  {{ _('Upload new album') }}
                </a>
              </li>
              <li class="nav-item mb-2">
                <a class="nav-link {{ 'active' if active_page == 'new_tour' }}" href="{{ url_for('tour.create') }}">
                  {{ _('Upload new tour') }}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">
                  {{ _('Logout') }}
                </a>
              </li>
              {% endif %}
            </ul>
            {% if request.endpoint %}
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Translate</span>
            </h6>
            <ul class="nav flex-column">
            {% for language in config['LANGUAGES'] %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for(request.endpoint, **dict(request.view_args, lang=language)) }}">
                 {{ language }}
                 {% if g.lang == language %}<span class="badge badge-info">Current</span>{% endif %}
              </a>
            </li>
            {% endfor %}
            </ul>
            {% endif %}
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block headline %}{% endblock %}</h1>
          </div>
          {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
              {% for type, content in messages %}
                <div class="alert alert-{{ type }} alert-dismissible my-4" role="alert">
                  <button type="button" class="close"
                          data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  {{ content }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </main>
      </div>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>