Flask/5-globomusic/app/tour/forms.py
# Extension for implementing WTForms for managing web forms
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired, DataRequired, Length, ValidationError
# Extension for implementing translations
from flask_babel import lazy_gettext as _l


# General Tour form
class TourForm(FlaskForm):
	title			= StringField(_l("Title"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=5, max=80, message="Title must be between 5 and 80 characters long")
								])
	artist			= StringField(_l("Artist"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=2, max=30, message="Artist name must be between 2 and 30 characters long")
								])
	description 	= TextAreaField(_l("Description"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=10, max=200, message="Description must be between 10 and 200 characters long")
								])
	genre			= StringField(_l("Genre"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!"),
									Length(min=2, max=20, message="Genre must be between 2 and 20 characters long")
								])
	start_date		= DateField(_l("Start date"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!")
								],
								format="%Y-%m-%d"
								)
	end_date		= DateField(_l("End date"),
								validators=[
									InputRequired("Input is required!"),
									DataRequired("Data is required!")
								],
								format="%Y-%m-%d"
								)

	def validate_start_date(form, field):
		if(field.data > form.end_date.data):
			raise ValidationError("Start date needs to be before the end date.")

# Form for creating new tours
class CreateTourForm(TourForm):
	submit 		= SubmitField(_l("Upload tour"))

# Form for updating a tour
class UpdateTourForm(TourForm):
	submit 		= SubmitField(_l("Update tour information"))

Flask/5-globomusic/app/tour/views.py
# Imports from Flask
from flask import Blueprint, render_template, flash, abort, url_for, redirect
# Extension for implementing Flask-Login for authentication
from flask_login import current_user, login_required
# Extension for implementing translations
from flask_babel import _
from flask_babel import lazy_gettext as _l
from app import db
from app.models import Tour
from app.tour.forms import CreateTourForm, UpdateTourForm

tour=Blueprint("tour", __name__, template_folder="templates")


# Route for listing tours
@tour.route("/")
@login_required
def list():
    tours = Tour.query.all()
    return render_template("list_tours.html", tours=tours)

# Route for creating new tours
@tour.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = CreateTourForm()

    if form.validate_on_submit():
        title        = form.title.data
        artist       = form.artist.data
        description  = form.description.data
        genre        = form.genre.data
        start_date   = form.start_date.data
        end_date     = form.end_date.data

        tour = Tour(title, artist, description, genre, start_date, end_date, current_user.id)
        db.session.add(tour)
        db.session.commit()
        flash(_("The new tour has been added."), "success")
        return redirect(url_for("tour.show", slug=tour.slug))

    return render_template("create_tour.html", form=form)

# Route for updating a tour
@tour.route("/edit/<slug>", methods=["GET", "POST"])
@login_required
def edit(slug):
    form = UpdateTourForm()

    tour = Tour.query.filter_by(slug=slug).first()

    if not tour or not current_user.is_tour_owner(tour):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))

    if form.validate_on_submit():
        title       = form.title.data
        artist      = form.artist.data
        description = form.description.data
        genre       = form.genre.data
        start_date  = form.start_date.data
        end_date    = form.end_date.data

        tour.title       = title
        tour.artist      = artist
        tour.description = description
        tour.genre       = genre
        tour.start_date  = start_date
        tour.end_date    = end_date

        db.session.add(tour)
        db.session.commit()
        flash(_("The tour has been updated."), "success")
        return redirect(url_for("tour.show", slug=tour.slug))

    form.title.data       = tour.title
    form.artist.data      = tour.artist
    form.description.data = tour.description
    form.genre.data       = tour.genre
    form.start_date.data  = tour.start_date
    form.end_date.data    = tour.end_date
    return render_template("edit_tour.html", tour=tour, form=form)

# Route for deleting a tour
@tour.route("/delete/<slug>", methods=["POST"])
@login_required
def delete(slug):
    tour = Tour.query.filter_by(slug=slug).first()
    if not tour or not current_user.is_tour_owner(tour):
        flash(_("You are not authorized to do this."), "danger")
        return redirect(url_for("main.home"))
    db.session.delete(tour)
    db.session.commit()
    flash(_("The tour has been deleted."), "success")
    return redirect(url_for("main.home"))

# Route for showing a tour
@tour.route("/show/<slug>")
@login_required
def show(slug):
    tour = Tour.query.filter_by(slug=slug).first()
    if not tour:
        abort(404)
    return render_template("show_tour.html", tour=tour)

Flask/5-globomusic/app/tour/templates/create_tour.html
{% extends 'base.html' %}
{% block headline %}{{ _('Upload new tour') }}{% endblock %}
{% from '_error_messages.html' import error_messages %}
{% set active_page = 'new_tour' %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <form method="POST" action="{{ url_for('tour.create') }}" enctype="multipart/form-data">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.artist.label }}
        {{ form.artist(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
      </div>
      <div class="form-group">
        {{ form.genre.label }}
        {{ form.genre(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.start_date.label }}<br>
        {{ form.start_date }}
      </div>
      <div class="form-group">
        {{ form.end_date.label }}<br>
        {{ form.end_date }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/5-globomusic/app/tour/templates/edit_tour.html
{% extends 'base.html' %}
{% block headline %}{{ _('Update tour information') }} - <a href="{{ url_for('show_tour', slug=tour.slug) }}">{{ tour.title }}</a>{% endblock %}
{% from '_error_messages.html' import error_messages %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <form method="POST" action="{{ url_for('tour.edit', slug=tour.slug) }}">
      {{ form.csrf_token }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.artist.label }}
        {{ form.artist(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control", rows="8") }}
      </div>
      <div class="form-group">
        {{ form.genre.label }}
        {{ form.genre(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.start_date.label }}<br>
        {{ form.start_date }}
      </div>
      <div class="form-group">
        {{ form.end_date.label }}<br>
        {{ form.end_date }}
      </div>
      <hr>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary form-control") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

Flask/5-globomusic/app/tour/templates/list_tours.html
{% extends 'base.html' %}
{% set active_page = 'tours' %}
{% block headline %}
  {{ _('Check out these tours') }}
{% endblock %}

{% block content %}
{% if tours %}
{% for tour in tours %}
<div class="card text-center mt-3 mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <h5 class="card-title"><a href="{{ url_for('tour.show', slug=tour.slug) }}">{{ tour.title }}</a></h5>
        <p class="card-text">{{ tour.artist }}</p>
      </div>
      <div class="col-md-4">
        <p class="card-text">{{ tour.description }}</p>
        <p class="card-text">{{ tour.genre }}</p>
      </div>
      <div class="col-md-4">
        <p class="card-text"><b>{{ _('From') }}</b> {{ tour.start_date | date_format }} <b>{{ _('to') }}</b> {{ tour.end_date | date_format }}</p>
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    {% if current_user.is_tour_owner(tour) %}
    {{ _('Posted by you') }}
    {% else %}
    {{ _('Posted by') }} {{ tour.user.username }}
    {% endif %}
  </div>
</div>
{% endfor %}
{% else %}
{{ _('There are no tours to show.') }}
{% endif %}
{% endblock %}

Flask/5-globomusic/app/tour/templates/show_tour.html
{% extends 'base.html' %}
{% block headline %}Tour "{{ tour.title }}"{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-5">
    <p><b>{{ _('Title') }}: </b>{{ tour.title }}</p>
    <p><b>{{ _('Artist') }}: </b>{{ tour.artist }}</p>
    <p><b>{{ _('Description') }}: </b>{{ tour.description }}</p>
    <p><b>{{ _('Genre') }}: </b>{{ tour.genre }}</p>
    <p><b>{{ _('Start date') }}: </b>{{ tour.start_date | date_format }}</p>
    <p><b>{{ _('End date') }}: </b>{{ tour.end_date | date_format }}</p>
    {% if current_user.is_tour_owner(tour) %}
    <a class="btn btn-info" href="{{ url_for('tour.edit', slug=tour.slug) }}">{{ _('Edit tour') }}</a>
    <form action="{{ url_for('tour.delete', slug=tour.slug) }}" style="display:inline" method="POST">
      <input type="submit" class="btn btn-danger" value="{{ _('Delete tour') }}" onclick="return confirm('{{ _('Are you sure that you want to permanently delete this tour?') }}')">
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}